// Generated by Dagger (https://google.github.io/dagger).
package com.selfcompany.faizf.seemovie.presentation.activity;

import com.selfcompany.faizf.newbase.manager.DialogManager;
import dagger.MembersInjector;
import javax.inject.Provider;

public final class BaseActivity_MembersInjector implements MembersInjector<BaseActivity> {
  private final Provider<DialogManager> dialogManagerProvider;

  public BaseActivity_MembersInjector(Provider<DialogManager> dialogManagerProvider) {
    this.dialogManagerProvider = dialogManagerProvider;
  }

  public static MembersInjector<BaseActivity> create(
      Provider<DialogManager> dialogManagerProvider) {
    return new BaseActivity_MembersInjector(dialogManagerProvider);
  }

  @Override
  public void injectMembers(BaseActivity instance) {
    injectDialogManager(instance, dialogManagerProvider.get());
  }

  public static void injectDialogManager(BaseActivity instance, DialogManager dialogManager) {
    instance.dialogManager = dialogManager;
  }
}
