// Generated by Dagger (https://google.github.io/dagger).
package com.selfcompany.faizf.seemovie.presentation.activity;

import com.selfcompany.faizf.newbase.manager.DialogManager;
import com.selfcompany.faizf.seemovie.presentation.detailmovie.DetailMovieActivity;
import com.selfcompany.faizf.seemovie.presentation.detailmovie.DetailMoviePres;

import javax.inject.Provider;

import dagger.MembersInjector;

public final class DetailMovieActivity_MembersInjector
    implements MembersInjector<DetailMovieActivity> {
  private final Provider<DialogManager> dialogManagerProvider;

  private final Provider<DetailMoviePres> presenterProvider;

  public DetailMovieActivity_MembersInjector(
      Provider<DialogManager> dialogManagerProvider, Provider<DetailMoviePres> presenterProvider) {
    this.dialogManagerProvider = dialogManagerProvider;
    this.presenterProvider = presenterProvider;
  }

  public static MembersInjector<DetailMovieActivity> create(
      Provider<DialogManager> dialogManagerProvider, Provider<DetailMoviePres> presenterProvider) {
    return new DetailMovieActivity_MembersInjector(dialogManagerProvider, presenterProvider);
  }

  @Override
  public void injectMembers(DetailMovieActivity instance) {
    BaseActivity_MembersInjector.injectDialogManager(instance, dialogManagerProvider.get());
    injectPresenter(instance, presenterProvider.get());
  }

  public static void injectPresenter(DetailMovieActivity instance, DetailMoviePres presenter) {
    instance.presenter = presenter;
  }
}
