// Generated by Dagger (https://google.github.io/dagger).
package com.selfcompany.faizf.seemovie.presentation.activity;

import com.selfcompany.faizf.newbase.manager.DialogManager;
import com.selfcompany.faizf.seemovie.presentation.maincontainer.MainActivity;
import com.selfcompany.faizf.seemovie.presentation.maincontainer.MainPres;

import dagger.MembersInjector;
import javax.inject.Provider;

public final class MainActivity_MembersInjector implements MembersInjector<MainActivity> {
  private final Provider<DialogManager> dialogManagerProvider;

  private final Provider<MainPres> presenterProvider;

  public MainActivity_MembersInjector(
      Provider<DialogManager> dialogManagerProvider, Provider<MainPres> presenterProvider) {
    this.dialogManagerProvider = dialogManagerProvider;
    this.presenterProvider = presenterProvider;
  }

  public static MembersInjector<MainActivity> create(
      Provider<DialogManager> dialogManagerProvider, Provider<MainPres> presenterProvider) {
    return new MainActivity_MembersInjector(dialogManagerProvider, presenterProvider);
  }

  @Override
  public void injectMembers(MainActivity instance) {
    BaseActivity_MembersInjector.injectDialogManager(instance, dialogManagerProvider.get());
    injectPresenter(instance, presenterProvider.get());
  }

  public static void injectPresenter(MainActivity instance, MainPres presenter) {
    instance.presenter = presenter;
  }
}
