// Generated by Dagger (https://google.github.io/dagger).
package com.selfcompany.faizf.seemovie.presentation.fragment;

import com.selfcompany.faizf.newbase.manager.DialogManager;
import com.selfcompany.faizf.newbase.utils.Util;
import com.selfcompany.faizf.seemovie.presentation.account.AccountFragment;

import dagger.MembersInjector;
import javax.inject.Provider;

public final class AccountFragment_MembersInjector implements MembersInjector<AccountFragment> {
  private final Provider<DialogManager> dialogManagerProvider;

  private final Provider<Util> utilProvider;

  public AccountFragment_MembersInjector(
      Provider<DialogManager> dialogManagerProvider, Provider<Util> utilProvider) {
    this.dialogManagerProvider = dialogManagerProvider;
    this.utilProvider = utilProvider;
  }

  public static MembersInjector<AccountFragment> create(
      Provider<DialogManager> dialogManagerProvider, Provider<Util> utilProvider) {
    return new AccountFragment_MembersInjector(dialogManagerProvider, utilProvider);
  }

  @Override
  public void injectMembers(AccountFragment instance) {
    BaseFragment_MembersInjector.injectDialogManager(instance, dialogManagerProvider.get());
    BaseFragment_MembersInjector.injectUtil(instance, utilProvider.get());
  }
}
