// Generated by Dagger (https://google.github.io/dagger).
package com.selfcompany.faizf.seemovie.presentation.fragment;

import com.selfcompany.faizf.newbase.manager.DialogManager;
import com.selfcompany.faizf.newbase.utils.Util;
import dagger.MembersInjector;
import javax.inject.Provider;

public final class BaseFragment_MembersInjector implements MembersInjector<BaseFragment> {
  private final Provider<DialogManager> dialogManagerProvider;

  private final Provider<Util> utilProvider;

  public BaseFragment_MembersInjector(
      Provider<DialogManager> dialogManagerProvider, Provider<Util> utilProvider) {
    this.dialogManagerProvider = dialogManagerProvider;
    this.utilProvider = utilProvider;
  }

  public static MembersInjector<BaseFragment> create(
      Provider<DialogManager> dialogManagerProvider, Provider<Util> utilProvider) {
    return new BaseFragment_MembersInjector(dialogManagerProvider, utilProvider);
  }

  @Override
  public void injectMembers(BaseFragment instance) {
    injectDialogManager(instance, dialogManagerProvider.get());
    injectUtil(instance, utilProvider.get());
  }

  public static void injectDialogManager(BaseFragment instance, DialogManager dialogManager) {
    instance.dialogManager = dialogManager;
  }

  public static void injectUtil(BaseFragment instance, Util util) {
    instance.util = util;
  }
}
