// Generated by Dagger (https://google.github.io/dagger).
package com.selfcompany.faizf.seemovie.presentation.fragment;

import com.selfcompany.faizf.newbase.manager.DialogManager;
import com.selfcompany.faizf.newbase.utils.Util;
import com.selfcompany.faizf.seemovie.presentation.cinema.CinemasFragment;

import dagger.MembersInjector;
import javax.inject.Provider;

public final class CinemasFragment_MembersInjector implements MembersInjector<CinemasFragment> {
  private final Provider<DialogManager> dialogManagerProvider;

  private final Provider<Util> utilProvider;

  public CinemasFragment_MembersInjector(
      Provider<DialogManager> dialogManagerProvider, Provider<Util> utilProvider) {
    this.dialogManagerProvider = dialogManagerProvider;
    this.utilProvider = utilProvider;
  }

  public static MembersInjector<CinemasFragment> create(
      Provider<DialogManager> dialogManagerProvider, Provider<Util> utilProvider) {
    return new CinemasFragment_MembersInjector(dialogManagerProvider, utilProvider);
  }

  @Override
  public void injectMembers(CinemasFragment instance) {
    BaseFragment_MembersInjector.injectDialogManager(instance, dialogManagerProvider.get());
    BaseFragment_MembersInjector.injectUtil(instance, utilProvider.get());
  }
}
