// Generated by Dagger (https://google.github.io/dagger).
package com.selfcompany.faizf.seemovie.presentation.fragment;

import com.selfcompany.faizf.newbase.manager.DialogManager;
import com.selfcompany.faizf.newbase.utils.Util;
import com.selfcompany.faizf.seemovie.presentation.fragment.slider.SliderFragment;

import dagger.MembersInjector;
import javax.inject.Provider;

public final class SliderFragment_MembersInjector implements MembersInjector<SliderFragment> {
  private final Provider<DialogManager> dialogManagerProvider;

  private final Provider<Util> utilProvider;

  public SliderFragment_MembersInjector(
      Provider<DialogManager> dialogManagerProvider, Provider<Util> utilProvider) {
    this.dialogManagerProvider = dialogManagerProvider;
    this.utilProvider = utilProvider;
  }

  public static MembersInjector<SliderFragment> create(
      Provider<DialogManager> dialogManagerProvider, Provider<Util> utilProvider) {
    return new SliderFragment_MembersInjector(dialogManagerProvider, utilProvider);
  }

  @Override
  public void injectMembers(SliderFragment instance) {
    BaseFragment_MembersInjector.injectDialogManager(instance, dialogManagerProvider.get());
    BaseFragment_MembersInjector.injectUtil(instance, utilProvider.get());
  }
}
